### ISSUE TITLE
Support for AR9565

### ISSUE THREAD

**Issue by Micael106** [ipang-dwi/atheros#1]
This kext will be compatible with AR9565?

**Comment by ipang-dwi** [comment]
no, just listed devices on readme that supported.. for ar9565, you can try kext from macwin on https://www.youtube.com/watch?v=HzzgLZgDGi8.. my friend just post in our local hackintosh group community, that it was working perfectly..

**Comment by Micael106** [comment]
It Works, but the speed is slow in some Wi-Fi router. Other It Works well. Thank you.

**Comment by ipang-dwi** [comment]
try this, this is from my another friend.. https://drive.google.com/file/d/1ZI0p0gHJkAXshSTxiSwsCVmPGwpJ8nom/view?fbclid=IwAR3CglkwU3JWYDgvTsoafKwVyif7B52M8jpnG0GqNKIiMCSRjGbA2sTaPVQ

**Comment by ipang-dwi** [comment]
this is the preview of it's speed.. https://pasteboard.co/J7sA8EO.jpg
