### ISSUE TITLE
OpenCore?

### ISSUE THREAD

**Issue by Schaka** [ipang-dwi/atheros#4]
Hey man,

I found your release for the backported Atheros cards for Catalina (entire IO80211 Family backported). I can't, however, get it to work with OpenCore. My WiFi never shows up and I've tried quite a few different things with different downloads. Have you ever gotten it to work on OpenCore?

If you have any ideas, let me know.
The best I could find in the opencore docs was this: https://dortania.github.io/Wireless-Buyers-Guide/Kext.html#atheros

**Comment by ipang-dwi** [comment]
Man, I am not a paranormal, can you give me an information, which atheros card type that you use. Also what Mac OS version you use too.

**Comment by Schaka** [comment]
Seems this adds too many kexts in Plugins folder.
I solved my issue by adding an empty IO80211 and the Atheros40 kext separately to my EFI kexts folder.
Basically this is what I went with and that worked for OpenCore: https://www.insanelymac.com/forum/files/file/1008-io80211family-modif/

**Comment by ipang-dwi** [comment]
Nice to hear that..
